
name: Build Singlefile 

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag version to env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set download path to env
        run: echo "DOWNLOAD_PATH=https://github.com/${{ env.GITHUB_REPOSITORY }}/releases/download/${{ env.RELEASE_VERSION }}/install" >> $GITHUB_ENV
      - name: Build single file installer
        run: chmod +x build.sh && ./build.sh ${{ env.DOWNLOAD_PATH }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "`curl -sfL ${{ env.DOWNLOAD_PATH }} | bash -`"
          files: install